Testing of the methods inside the enumerable module
LOctavio/enumerable-methods pull request #5
Opened 2020-05-01 21:16 UTC by muhenge

## Tests done are
- Checking all methods without parameters,
- All methods with parameters,
- All the methods that have blocks and parameters at the same time  
- All methods without blocks and with blocks.

2020-05-04 05:06 UTC, kobiyoyo requested changes
## Hi  Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, Just few things to work on. 
### General
check the comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-05-04 05:06 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
- Lets write test for when reqex is given
- Also write for when no block or argument is given

2020-05-04 05:06 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
- Lets write test for when reqex is given
- Also write for when no block or argument is given
- Lastly lets write for when a class is passed as an argument

2020-05-04 05:06 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
- Lets write test for when reqex is given
- Also write for when no block or argument is given
- Lastly lets write for when a class is passed as an argument

2020-05-05 19:04 UTC, mosesogwo requested changes
**Hi team:clap: Good job, but one kind of test recommended from the previous review is still not here**
- When a class is given as argument to **my_any?** and **my_none?**. You have a similar kind of test for my_all? You now have to add such test for my_any? and my_none?
Here's one from my_all?
```
      it 'all the values are not Strings' do
        expect([8, 4, 3, 9, 5].my_all?(String)).to eql(false)
      end
```
_**Kindly make this change and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-05-06 13:00 UTC, Torres-ssf approved these changes
### Project Approved :tada: :+1: 
Hi there team :hand: 
Congratulations on implementing testing for your enumarable methods. I can see that many tests were implemented and you also worked on the requested changes. :clap: 
This PR is approved. you can merge it now :smile: 

**TIP**
I notice the README file is missing one of the Authors

Happy coding :computer: 
**Sergio Torres**

2020-05-06 15:16 UTC, merged